-- MySQL Script generated by MySQL Workbench
-- Sun Jul  7 00:17:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controle` DEFAULT CHARACTER SET utf8 ;
USE `controle` ;

-- -----------------------------------------------------
-- Table `controle`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle`.`produto` (
  `idproduto` INT NOT NULL,
  `tipoProduto` VARCHAR(150) NOT NULL,
  `qtdeProduto` INT NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle`.`usuarios` (
  `idusuarios` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
